name: markdownlint

on: [push, pull_request]

jobs:
  markdownlint:
    runs-on: ubuntu-latest
    steps:
    - name: Check out code
      uses: actions/checkout@master
    - name: markdownlint-cli
      uses: nosborn/github-action-markdown-cli@v2.0.0
      with:
        files: .
        config_file: ".markdownlint.yaml"
        ignore_files: "assets/*"
